version: '3.3'
services:
  redis:
    image: redis
    command: redis-server
    container_name: stock_redis
    ports:
      - "14000:6379"

  database:
    container_name: stock_database
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data

  django:
    container_name: stock_app
    build:
      context: ./django/
    restart: always
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./django/:/code
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

volumes:
  database_data: